/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as PiggyverseRouteImport } from './routes/piggyverse'
import { Route as EthosRouteImport } from './routes/ethos'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as UsersRouteRouteImport } from './routes/users.route'
import { Route as PostsRouteRouteImport } from './routes/posts.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as CollectorIndexRouteImport } from './routes/collector.index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as PlayLeaderboardRouteImport } from './routes/play.leaderboard'
import { Route as PlayFlappyPigRouteImport } from './routes/play.flappy-pig'
import { Route as DemoHoloCardsRouteImport } from './routes/demo.holo-cards'
import { Route as CollectorUpdateRouteImport } from './routes/collector.update'
import { Route as CollectorReservationRouteImport } from './routes/collector.reservation'
import { Route as CollectorOgRouteImport } from './routes/collector.og'
import { Route as CollectorNewRouteImport } from './routes/collector.new'
import { Route as CollectorDiscordRouteImport } from './routes/collector.discord'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as PostsPostIdDeepRouteImport } from './routes/posts_.$postId.deep'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'
import { ServerRoute as ApiUsersServerRouteImport } from './routes/api.users'
import { ServerRoute as ApiUsersIdServerRouteImport } from './routes/api/users.$id'

const rootServerRouteImport = createServerRootRoute()

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const PiggyverseRoute = PiggyverseRouteImport.update({
  id: '/piggyverse',
  path: '/piggyverse',
  getParentRoute: () => rootRouteImport,
} as any)
const EthosRoute = EthosRouteImport.update({
  id: '/ethos',
  path: '/ethos',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRouteRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const CollectorIndexRoute = CollectorIndexRouteImport.update({
  id: '/collector/',
  path: '/collector/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRouteRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRouteRoute,
} as any)
const PlayLeaderboardRoute = PlayLeaderboardRouteImport.update({
  id: '/play/leaderboard',
  path: '/play/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayFlappyPigRoute = PlayFlappyPigRouteImport.update({
  id: '/play/flappy-pig',
  path: '/play/flappy-pig',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoHoloCardsRoute = DemoHoloCardsRouteImport.update({
  id: '/demo/holo-cards',
  path: '/demo/holo-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorUpdateRoute = CollectorUpdateRouteImport.update({
  id: '/collector/update',
  path: '/collector/update',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorReservationRoute = CollectorReservationRouteImport.update({
  id: '/collector/reservation',
  path: '/collector/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorOgRoute = CollectorOgRouteImport.update({
  id: '/collector/og',
  path: '/collector/og',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorNewRoute = CollectorNewRouteImport.update({
  id: '/collector/new',
  path: '/collector/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorDiscordRoute = CollectorDiscordRouteImport.update({
  id: '/collector/discord',
  path: '/collector/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PostsPostIdDeepRoute = PostsPostIdDeepRouteImport.update({
  id: '/posts_/$postId/deep',
  path: '/posts/$postId/deep',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const ApiUsersServerRoute = ApiUsersServerRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiUsersIdServerRoute = ApiUsersIdServerRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersServerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/ethos': typeof EthosRoute
  '/piggyverse': typeof PiggyverseRoute
  '/redirect': typeof RedirectRoute
  '/collector/discord': typeof CollectorDiscordRoute
  '/collector/new': typeof CollectorNewRoute
  '/collector/og': typeof CollectorOgRoute
  '/collector/reservation': typeof CollectorReservationRoute
  '/collector/update': typeof CollectorUpdateRoute
  '/demo/holo-cards': typeof DemoHoloCardsRoute
  '/play/flappy-pig': typeof PlayFlappyPigRoute
  '/play/leaderboard': typeof PlayLeaderboardRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/collector': typeof CollectorIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/ethos': typeof EthosRoute
  '/piggyverse': typeof PiggyverseRoute
  '/redirect': typeof RedirectRoute
  '/collector/discord': typeof CollectorDiscordRoute
  '/collector/new': typeof CollectorNewRoute
  '/collector/og': typeof CollectorOgRoute
  '/collector/reservation': typeof CollectorReservationRoute
  '/collector/update': typeof CollectorUpdateRoute
  '/demo/holo-cards': typeof DemoHoloCardsRoute
  '/play/flappy-pig': typeof PlayFlappyPigRoute
  '/play/leaderboard': typeof PlayLeaderboardRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/collector': typeof CollectorIndexRoute
  '/posts': typeof PostsIndexRoute
  '/users': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/ethos': typeof EthosRoute
  '/piggyverse': typeof PiggyverseRoute
  '/redirect': typeof RedirectRoute
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/collector/discord': typeof CollectorDiscordRoute
  '/collector/new': typeof CollectorNewRoute
  '/collector/og': typeof CollectorOgRoute
  '/collector/reservation': typeof CollectorReservationRoute
  '/collector/update': typeof CollectorUpdateRoute
  '/demo/holo-cards': typeof DemoHoloCardsRoute
  '/play/flappy-pig': typeof PlayFlappyPigRoute
  '/play/leaderboard': typeof PlayLeaderboardRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/collector/': typeof CollectorIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/posts_/$postId/deep': typeof PostsPostIdDeepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/users'
    | '/deferred'
    | '/ethos'
    | '/piggyverse'
    | '/redirect'
    | '/collector/discord'
    | '/collector/new'
    | '/collector/og'
    | '/collector/reservation'
    | '/collector/update'
    | '/demo/holo-cards'
    | '/play/flappy-pig'
    | '/play/leaderboard'
    | '/posts/$postId'
    | '/users/$userId'
    | '/collector'
    | '/posts/'
    | '/users/'
    | '/route-a'
    | '/route-b'
    | '/posts/$postId/deep'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deferred'
    | '/ethos'
    | '/piggyverse'
    | '/redirect'
    | '/collector/discord'
    | '/collector/new'
    | '/collector/og'
    | '/collector/reservation'
    | '/collector/update'
    | '/demo/holo-cards'
    | '/play/flappy-pig'
    | '/play/leaderboard'
    | '/posts/$postId'
    | '/users/$userId'
    | '/collector'
    | '/posts'
    | '/users'
    | '/route-a'
    | '/route-b'
    | '/posts/$postId/deep'
  id:
    | '__root__'
    | '/'
    | '/posts'
    | '/users'
    | '/_pathlessLayout'
    | '/deferred'
    | '/ethos'
    | '/piggyverse'
    | '/redirect'
    | '/_pathlessLayout/_nested-layout'
    | '/collector/discord'
    | '/collector/new'
    | '/collector/og'
    | '/collector/reservation'
    | '/collector/update'
    | '/demo/holo-cards'
    | '/play/flappy-pig'
    | '/play/leaderboard'
    | '/posts/$postId'
    | '/users/$userId'
    | '/collector/'
    | '/posts/'
    | '/users/'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/posts_/$postId/deep'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  UsersRouteRoute: typeof UsersRouteRouteWithChildren
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  DeferredRoute: typeof DeferredRoute
  EthosRoute: typeof EthosRoute
  PiggyverseRoute: typeof PiggyverseRoute
  RedirectRoute: typeof RedirectRoute
  CollectorDiscordRoute: typeof CollectorDiscordRoute
  CollectorNewRoute: typeof CollectorNewRoute
  CollectorOgRoute: typeof CollectorOgRoute
  CollectorReservationRoute: typeof CollectorReservationRoute
  CollectorUpdateRoute: typeof CollectorUpdateRoute
  DemoHoloCardsRoute: typeof DemoHoloCardsRoute
  PlayFlappyPigRoute: typeof PlayFlappyPigRoute
  PlayLeaderboardRoute: typeof PlayLeaderboardRoute
  CollectorIndexRoute: typeof CollectorIndexRoute
  PostsPostIdDeepRoute: typeof PostsPostIdDeepRoute
}
export interface FileServerRoutesByFullPath {
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/users/$id': typeof ApiUsersIdServerRoute
}
export interface FileServerRoutesByTo {
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/users/$id': typeof ApiUsersIdServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/users/$id': typeof ApiUsersIdServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/users' | '/api/users/$id'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/users' | '/api/users/$id'
  id: '__root__' | '/api/users' | '/api/users/$id'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiUsersServerRoute: typeof ApiUsersServerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piggyverse': {
      id: '/piggyverse'
      path: '/piggyverse'
      fullPath: '/piggyverse'
      preLoaderRoute: typeof PiggyverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethos': {
      id: '/ethos'
      path: '/ethos'
      fullPath: '/ethos'
      preLoaderRoute: typeof EthosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/collector/': {
      id: '/collector/'
      path: '/collector'
      fullPath: '/collector'
      preLoaderRoute: typeof CollectorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/play/leaderboard': {
      id: '/play/leaderboard'
      path: '/play/leaderboard'
      fullPath: '/play/leaderboard'
      preLoaderRoute: typeof PlayLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/flappy-pig': {
      id: '/play/flappy-pig'
      path: '/play/flappy-pig'
      fullPath: '/play/flappy-pig'
      preLoaderRoute: typeof PlayFlappyPigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/holo-cards': {
      id: '/demo/holo-cards'
      path: '/demo/holo-cards'
      fullPath: '/demo/holo-cards'
      preLoaderRoute: typeof DemoHoloCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/update': {
      id: '/collector/update'
      path: '/collector/update'
      fullPath: '/collector/update'
      preLoaderRoute: typeof CollectorUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/reservation': {
      id: '/collector/reservation'
      path: '/collector/reservation'
      fullPath: '/collector/reservation'
      preLoaderRoute: typeof CollectorReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/og': {
      id: '/collector/og'
      path: '/collector/og'
      fullPath: '/collector/og'
      preLoaderRoute: typeof CollectorOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/new': {
      id: '/collector/new'
      path: '/collector/new'
      fullPath: '/collector/new'
      preLoaderRoute: typeof CollectorNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/discord': {
      id: '/collector/discord'
      path: '/collector/discord'
      fullPath: '/collector/discord'
      preLoaderRoute: typeof CollectorDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/posts_/$postId/deep': {
      id: '/posts_/$postId/deep'
      path: '/posts/$postId/deep'
      fullPath: '/posts/$postId/deep'
      preLoaderRoute: typeof PostsPostIdDeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdServerRouteImport
      parentRoute: typeof ApiUsersServerRoute
    }
  }
}

interface PostsRouteRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

interface UsersRouteRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteRouteChildren: UsersRouteRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteRouteWithChildren = UsersRouteRoute._addFileChildren(
  UsersRouteRouteChildren,
)

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface ApiUsersServerRouteChildren {
  ApiUsersIdServerRoute: typeof ApiUsersIdServerRoute
}

const ApiUsersServerRouteChildren: ApiUsersServerRouteChildren = {
  ApiUsersIdServerRoute: ApiUsersIdServerRoute,
}

const ApiUsersServerRouteWithChildren = ApiUsersServerRoute._addFileChildren(
  ApiUsersServerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  UsersRouteRoute: UsersRouteRouteWithChildren,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  DeferredRoute: DeferredRoute,
  EthosRoute: EthosRoute,
  PiggyverseRoute: PiggyverseRoute,
  RedirectRoute: RedirectRoute,
  CollectorDiscordRoute: CollectorDiscordRoute,
  CollectorNewRoute: CollectorNewRoute,
  CollectorOgRoute: CollectorOgRoute,
  CollectorReservationRoute: CollectorReservationRoute,
  CollectorUpdateRoute: CollectorUpdateRoute,
  DemoHoloCardsRoute: DemoHoloCardsRoute,
  PlayFlappyPigRoute: PlayFlappyPigRoute,
  PlayLeaderboardRoute: PlayLeaderboardRoute,
  CollectorIndexRoute: CollectorIndexRoute,
  PostsPostIdDeepRoute: PostsPostIdDeepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiUsersServerRoute: ApiUsersServerRouteWithChildren,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
